### ISSUE TITLE
OutOfBoundsException on doctrine:mapping:graphviz

### ISSUE THREAD

**Issue by pborreli** [alexandresalome/doctrine-extra-bundle#2]
[OutOfBoundsException]
  Unexpected count of ":" in entity name. Expected one ("AcmeDemoBundle:User"), got 1 ("Application\Sonata\PageBundle\Entity\Block").

**Comment by rjmunro** [comment]
I think this is fixed in my fork (PR #3) - I allow clustering on entities identified by fully qualified names (i.e. with `\` instead of `:`.

**Comment by OskarStark** [comment]
refs #10 

i already have this error

**Comment by rjmunro** [comment]
This has probably been fixed now that v0.2.1 is out which contains #3.

**Comment by mvhirsch** [comment]
Yes, it works with v0.2.1, this issue can be closed.
