### ISSUE TITLE
The bundle throws an exception when metadata contains full entity namespaces instead of the entity's alias

### ISSUE THREAD

**Issue by csarrazi** [alexandresalome/doctrine-extra-bundle#5]
@alexandresalome, I'll describe this a little bit later (this week-end), as I have my hands full, right now! :)

**Comment by alexandresalome** [comment]
OK but the description seems pretty clear :)

**Comment by csarrazi** [comment]
Yeah, but I'll give you the exact line, stacktrace, etc. :)

**Comment by rjmunro** [comment]
I think this is a duplicate of #2, fixed in #3.

**Comment by csarrazi** [comment]
Dont' really think so, because I still had an error when using FQCNs, and not entity aliases. Unless a new version has been tagged in-between. In this case, this could be solved by creating a new tag.

Btw, you up for :beers:, @alexandresalome, on 07/22 or 07/23? ;)
